ERROR - 2020-05-09 16:23:15 --> An exception occured in driver: SQLSTATE[HY000] [2002] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 
ERROR - 2020-05-09 16:23:15 --> noActiveTransaction: C:\Users\pipo\Documents\wamp\www\facturacion\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php Line: 1266 
ERROR - 2020-05-09 16:23:15 --> rollBack: C:\Users\pipo\Documents\wamp\www\facturacion\system\Core\Doctrine.php Line: 72 
ERROR - 2020-05-09 16:23:15 --> rollBack: C:\Users\pipo\Documents\wamp\www\facturacion\app\controllers\LoginController.php Line: 82 
ERROR - 2020-05-09 16:23:15 --> call_user_func_array: C:\Users\pipo\Documents\wamp\www\facturacion\system\Core\Controller.php Line: 74 
ERROR - 2020-05-09 16:23:15 --> _reallocation: C:\Users\pipo\Documents\wamp\www\facturacion\bootstrap\app.php Line: 96 
ERROR - 2020-05-09 16:23:15 --> require: C:\Users\pipo\Documents\wamp\www\facturacion\index.php Line: 75 
ERROR - 2020-05-09 16:28:10 --> An exception occured in driver: SQLSTATE[HY000] [2002] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 
ERROR - 2020-05-09 16:28:10 --> noActiveTransaction: C:\Users\pipo\Documents\wamp\www\facturacion\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php Line: 1266 
ERROR - 2020-05-09 16:28:10 --> rollBack: C:\Users\pipo\Documents\wamp\www\facturacion\system\Core\Doctrine.php Line: 72 
ERROR - 2020-05-09 16:28:10 --> rollBack: C:\Users\pipo\Documents\wamp\www\facturacion\app\controllers\LoginController.php Line: 82 
ERROR - 2020-05-09 16:28:10 --> call_user_func_array: C:\Users\pipo\Documents\wamp\www\facturacion\system\Core\Controller.php Line: 74 
ERROR - 2020-05-09 16:28:10 --> _reallocation: C:\Users\pipo\Documents\wamp\www\facturacion\bootstrap\app.php Line: 96 
ERROR - 2020-05-09 16:28:10 --> require: C:\Users\pipo\Documents\wamp\www\facturacion\index.php Line: 75 
ERROR - 2020-05-09 16:29:24 --> An exception occured in driver: SQLSTATE[HY000] [2002] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 
ERROR - 2020-05-09 16:29:24 --> noActiveTransaction: C:\Users\pipo\Documents\wamp\www\facturacion\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php Line: 1266 
ERROR - 2020-05-09 16:29:24 --> rollBack: C:\Users\pipo\Documents\wamp\www\facturacion\system\Core\Doctrine.php Line: 72 
ERROR - 2020-05-09 16:29:24 --> rollBack: C:\Users\pipo\Documents\wamp\www\facturacion\app\controllers\LoginController.php Line: 82 
ERROR - 2020-05-09 16:29:24 --> call_user_func_array: C:\Users\pipo\Documents\wamp\www\facturacion\system\Core\Controller.php Line: 74 
ERROR - 2020-05-09 16:29:24 --> _reallocation: C:\Users\pipo\Documents\wamp\www\facturacion\bootstrap\app.php Line: 96 
ERROR - 2020-05-09 16:29:24 --> require: C:\Users\pipo\Documents\wamp\www\facturacion\index.php Line: 75 
